# Generated by Django 4.2.1 on 2023-06-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viberbotapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
