# Generated by Django 4.2 on 2023-05-14 09:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ClothCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothCategory', models.CharField(max_length=25, verbose_name='Категория домашней одежды')),
            ],
            options={
                'verbose_name': 'Категория домашней одежды',
                'verbose_name_plural': 'Категории домашней одежды',
            },
        ),
        migrations.CreateModel(
            name='ClothSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth', models.CharField(max_length=25, verbose_name='Размер одежды')),
            ],
            options={
                'verbose_name': 'Размер одежды',
                'verbose_name_plural': 'Размеры одежды',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=40, verbose_name='Color css')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Duvet_size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duvet_size', models.CharField(max_length=20, verbose_name='Размер пододеяльника')),
            ],
            options={
                'verbose_name': 'Размер пододеяльника',
                'verbose_name_plural': 'Размеры пододеяльника',
            },
        ),
        migrations.CreateModel(
            name='Filler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filler', models.CharField(max_length=25, verbose_name='Наполнитель')),
            ],
            options={
                'verbose_name': 'Наполнитель',
                'verbose_name_plural': 'Наполнители',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название соц-сети')),
                ('url', models.URLField(verbose_name='Ссылка на соц-сеть')),
            ],
            options={
                'verbose_name': 'Ссылки на соц-сети',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=30, verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=25, verbose_name='Номер заказа')),
                ('user_first_name', models.CharField(max_length=25, null=True, verbose_name='Имя')),
                ('user_last_name', models.CharField(max_length=25, null=True, verbose_name='Фамилия')),
                ('user_email', models.EmailField(max_length=254, null=True, verbose_name='Email заказчика')),
                ('user_phone', models.CharField(max_length=20, null=True, verbose_name='Номер телефона')),
                ('delivery_method', models.CharField(max_length=50, null=True, verbose_name='Способ доставки')),
                ('delivery_city', models.CharField(max_length=255, null=True, verbose_name='Город Доставки')),
                ('delivery_department', models.CharField(max_length=255, null=True, verbose_name='Отделение Новой Почты')),
                ('delivery_street', models.CharField(max_length=255, null=True, verbose_name='Адрес доставки курьером')),
                ('payment_method', models.CharField(max_length=50, null=True, verbose_name='Способ оплаты')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
                ('feedback', models.BooleanField(default=False, verbose_name='Хочет ли заказчик обратной связи')),
                ('feedback_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Способ обратной связи')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Время (Когда сервер принял заказ)')),
                ('articles', models.TextField(null=True, verbose_name='Артикли заказанных товаров')),
                ('processed', models.BooleanField(default=False, verbose_name='Заказ обработан?')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['processed', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Pillow_case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillow_case', models.CharField(max_length=20, verbose_name='Размер наволочек')),
            ],
            options={
                'verbose_name': 'Размер наволочки',
                'verbose_name_plural': 'Размеры наволочок',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.IntegerField(validators=[django.core.validators.RegexValidator('^-?\\d{1,30}$', 'ID должен содержать только цифры и знак минуса.')], verbose_name='Номер/Артикль')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='Цена со скидкой')),
                ('counter', models.IntegerField(blank=True, null=True, verbose_name='Количество')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='torry.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='torry.category', verbose_name='Категория')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='torry.color', verbose_name='Цвет')),
                ('duvet_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='torry.duvet_size', verbose_name='Размер пододеяльника')),
                ('filler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='torry.filler', verbose_name='Наполнитель')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='torry.material', verbose_name='Материал')),
                ('pillow_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='torry.pillow_case', verbose_name='Размер подушки')),
                ('robe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='torry.clothsize', verbose_name='Размер одежды')),
                ('robe_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='torry.clothcategory', verbose_name='Категория домашней одежды')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товар',
            },
        ),
        migrations.CreateModel(
            name='RugSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rug_size', models.CharField(max_length=25, verbose_name='Размер Коврика')),
            ],
            options={
                'verbose_name': 'Размер коврика',
                'verbose_name_plural': 'Размер ковриков',
            },
        ),
        migrations.CreateModel(
            name='Sheet_size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_size', models.CharField(max_length=20, verbose_name='Размер простыни')),
            ],
            options={
                'verbose_name': 'Размер простыни',
                'verbose_name_plural': 'Размеры простыни',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20, verbose_name='Общий размер')),
            ],
            options={
                'verbose_name': 'Общий размер',
                'verbose_name_plural': 'Общие размеры',
            },
        ),
        migrations.CreateModel(
            name='TowelSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('towel', models.CharField(max_length=25, verbose_name='Полотенца')),
            ],
            options={
                'verbose_name': 'Размер полотенца',
                'verbose_name_plural': 'Размеры полотенц',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bed_images/', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torry.product')),
            ],
            options={
                'verbose_name': 'Изображения выбранного продукта',
                'verbose_name_plural': 'Изображения выбранного продукта',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='rug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='torry.rugsize', verbose_name='Размер коврика'),
        ),
        migrations.AddField(
            model_name='product',
            name='sheet_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='torry.sheet_size', verbose_name='Размер простыни'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='torry.size', verbose_name='Общий размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='towel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='torry.towelsize', verbose_name='Размер полотенца'),
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='category_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torry.category')),
            ],
        ),
    ]
