# Generated by Django 4.2.1 on 2023-05-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torry', '0004_alter_product_discount_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='notes',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание'),
        ),
    ]
