# Generated by Django 4.2.1 on 2023-05-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torry', '0005_alter_product_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
